server:
  port: ${GATEWAY_SERVER_PORT}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: monitoring
          uri: 'lb://auth'
          predicates:
            - Path=/api/auth/**
        - id: music
          uri: 'lb://music'
          predicates:
            - Path=/api/music/**

eureka:
  client:
    register-with-eureka: false

# metricas con actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info
  endpoint:
    prometheus:
      enabled: true