server:
  port: ${MUSIC_SERVER_PORT}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true

# metricas con actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info
  endpoint:
    prometheus:
      enabled: true

test:
  api:
    nextcloud:
        uri: ${NEXTCLOUD_URI}
        username: ${TEST_NEXTCLOUD_USERNAME}
        password: ${TEST_NEXTCLOUD_PASSWORD}