server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: Config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations