spring:
  application:
    name: Eureka
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8761
eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false # No se registra a si mismo en el descubrimiento
        fetch-registry: false # Los servicios que se conecten no se descargan del descubrimiento
        serverUrl:
          defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
