services:
  cloud-storage-db:
    image: luishidalgoa/cloud-storage-db
    container_name: cloud-storage-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextclouduser
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - cloud-storage-network
    
  levelcloud-dev-container:
    image: luishidalgoa/levelcloud-dev-container:latest
    container_name: levelcloud-dev-container
    ports:
      - "22:22"
      - "8084:8084"
      - "8085:8085"
      - "8081:8081"
      - "8080:8080"
    volumes:
      - C:\Users\luish\Downloads\cloud-storage-dev:/tmp/MusicDownload  # Volumen para acceso desde Windows
    networks:
      - cloud-storage-network
      
  nextcloud-server:
    image: luishidalgoa/nextcloud-server:latest
    container_name: nextcloud-server
    ports:
      - "22:22"
      - "80:80"
    networks:
      - cloud-storage-network
networks:
  cloud-storage-network:
    driver: bridge
