services:
  cloud-storage-db:
    image: luishidalgoa/cloud-storage-db
    container_name: cloud-storage-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextclouduser
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - cloud-storage-network

  cloud-storage-dev:
    image: luishidalgoa/cloud-storage-dev
    container_name: cloud-storage-dev
    ports:
      - "22:22"
      - "80:80"
    networks:
      - cloud-storage-network

  # Monitoreo
  grafana:
    container_name: monitoring-grafana
    image: grafana/grafana:latest
    hostname: rpi-grafana
    restart: unless-stopped
    user: "472"
    networks:
      - monitoring
    ports:
      - "3000:3000"

  prometheus:
    container_name: monitoring-prometheus
    image: prom/prometheus:latest
    hostname: rpi-prometheus
    restart: unless-stopped
    user: "nobody"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
    networks:
      - monitoring
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - ./Monitoring/Prometheus/data:/prometheus
      - ./Monitoring/Prometheus:/etc/prometheus/

networks:
  cloud-storage-network:
    driver: bridge