name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Microservicios/Spring_project/pom.xml' # Solo ejecuta el build si cambia algún pom.xml
  pull_request:
    branches:
      - master # O la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t luishidalgoa/hidalgo-music:latest --push ./Microservicios/Spring_project/music
        
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Este job solo se ejecuta si el job 'build' fue exitoso
    environment: production
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/luish/scripts
            ./deploy.sh
